[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
# Removed startCommand to use Dockerfile ENTRYPOINT instead
# startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[[volumes]]
mountPath = "/data"
